///button_set_preview_bg()
with(obj_app_background_color_picker)
{
    with(obj_highlight_color_picker)
    {
        my_color_picker=instance_kill(my_color_picker);
        my_color_slider=instance_kill(my_color_slider);
    }
    with(obj_bg_color_picker)
    {
        my_color_picker=instance_kill(my_color_picker);
        my_color_slider=instance_kill(my_color_slider);
    }
    event_user(0);
}
